name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - name: Run linter
      run: |
        # For PR branches, only lint changed files to avoid failing on pre-existing issues
        # For master/main, we can run full linting once the codebase is cleaned up
        if [ "${{ github.ref }}" != "refs/heads/master" ] && [ "${{ github.ref }}" != "refs/heads/main" ]; then
          echo "Running linter on changed files only..."
          # Fetch master branch for comparison
          git fetch origin master:master 2>/dev/null || git fetch origin main:main 2>/dev/null || true
          BASE_BRANCH=$(git rev-parse --verify master 2>/dev/null || git rev-parse --verify main 2>/dev/null || echo "260d717")
          CHANGED_FILES=$(git diff --name-only --diff-filter=ACM $BASE_BRANCH...HEAD | grep -E '\.(js|ts|cjs)$' | xargs || true)
          if [ -n "$CHANGED_FILES" ]; then
            echo "Linting: $CHANGED_FILES"
            npx xo $CHANGED_FILES
          else
            echo "No JavaScript/TypeScript files changed"
          fi
        else
          echo "On master/main branch - skipping full lint until codebase is cleaned up"
          echo "Developers should run 'npm test' locally before committing"
        fi
      env:
        CI: true
